### ISSUE TITLE
Cannot find module './binding.node'

### ISSUE THREAD

**Issue by sarscoders** [ronomon/reed-solomon#8]
Error: Cannot find module './binding.node'
Require stack:
- E:\nodejs\reed-solomon-master\benchmark.js
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:864:27)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:1044:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:77:18)[39m
    at Object.<anonymous> (E:\nodejs\reed-solomon-master\benchmark.js:8:19)
[90m    at Module._compile (internal/modules/cjs/loader.js:1158:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:1002:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:901:14)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: [ [32m'E:\\nodejs\\reed-solomon-master\\benchmark.js'[39m ]
}

I am getting Cannot find module './binding.node' error you have used 
var ReedSolomon = require('./binding.node'); code in line no 5 of test.js code

**Comment by HanzCEO** [comment]
Run `node-gyp rebuild` in the package directory
